name: Build, Push and Deploy a Docker Image
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: OSO-Assigner-Bot-Team/j0bg1va
  name: Build, Push and Deploy a Docker Image
