name: Build, Push and Deploy a Docker Image
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: { secrets.REPO_NAME }
  name: Build, Push and Deploy a Docker Image
